import type { components } from '../generated/openapi'

export type AdminSession = components['schemas']['AdminSession']
export type Image = components['schemas']['Image']
export type ImageList = components['schemas']['ImageList']
export type ImageDetail = components['schemas']['ImageDetail']
export type DeleteImageResult = components['schemas']['DeleteImageResult']
export type BatchOperationResult = components['schemas']['BatchOperationResult']
export type Visibility = components['schemas']['Visibility']
export type ApiTokenScope = components['schemas']['ApiTokenScope']
export type ApiToken = components['schemas']['ApiToken']
export type ApiTokenList = components['schemas']['ApiTokenList']
export type CreatedApiToken = components['schemas']['CreatedApiToken']
export type AppSettings = components['schemas']['AppSettings']
export type SystemInfo = components['schemas']['SystemInfo']
export type SystemOverview = components['schemas']['SystemOverview']
export type InspectionResult = components['schemas']['InspectionResult']
export type RebuildResult = components['schemas']['RebuildResult']
export type ImageAlias = components['schemas']['ImageAlias']
export type ImageAliasList = components['schemas']['ImageAliasList']
